/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { QuizScores, QuizScoresInterface } from "../QuizScores";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "score",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "total",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ScoreSubmitted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "getScore",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "score",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "total",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct QuizScores.Score",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "scores",
    outputs: [
      {
        internalType: "uint8",
        name: "score",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "total",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "score",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "total",
        type: "uint8",
      },
    ],
    name: "submitScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610340806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806376dd110f14610046578063d120d01d1461009f578063d47875d0146100b4575b600080fd5b61007a610054366004610291565b6000602081905290815260409020805460019091015460ff808316926101009004169083565b6040805160ff9485168152939092166020840152908201526060015b60405180910390f35b6100b26100ad3660046102d7565b610148565b005b61011e6100c2366004610291565b6040805160608082018352600080835260208084018290529284018190526001600160a01b039490941684528382529282902082519384018352805460ff80821686526101009091041691840191909152600101549082015290565b60408051825160ff9081168252602080850151909116908201529181015190820152606001610096565b60008160ff16116101a05760405162461bcd60e51b815260206004820152601c60248201527f546f74616c206d7573742062652067726561746572207468616e20300000000060448201526064015b60405180910390fd5b8060ff168260ff1611156101f65760405162461bcd60e51b815260206004820152601960248201527f53636f72652063616e6e6f742065786365656420746f74616c000000000000006044820152606401610197565b604080516060808201835260ff8581168084528582166020808601828152428789018181523360008181528086528b902099518a54945189166101000261ffff19909516981697909717929092178855905160019097019690965586519283528201529384019290925290917f95d71264cfacf944422c8ffa4a8b9904b76ea2febd6d2c4450a72f991732dac5910160405180910390a25050565b6000602082840312156102a357600080fd5b81356001600160a01b03811681146102ba57600080fd5b9392505050565b803560ff811681146102d257600080fd5b919050565b600080604083850312156102ea57600080fd5b6102f3836102c1565b9150610301602084016102c1565b9050925092905056fea264697066735822122095f746d726fb0075607cd79423cd756308172f4b84b6057ae7478f67b2810d9964736f6c63430008140033";

type QuizScoresConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: QuizScoresConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class QuizScores__factory extends ContractFactory {
  constructor(...args: QuizScoresConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      QuizScores & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): QuizScores__factory {
    return super.connect(runner) as QuizScores__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): QuizScoresInterface {
    return new Interface(_abi) as QuizScoresInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): QuizScores {
    return new Contract(address, _abi, runner) as unknown as QuizScores;
  }
}
