const CHAIN_CONFIGS = {
  ink: {
    name: 'Ink',
    chainId: 57073,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    color: '#8b5cf6',
    rpc: 'https://rpc-gel.inkonchain.com',
    explorer: 'https://explorer.inkonchain.com',
    blockscoutApi: 'https://explorer.inkonchain.com/api/v2',
    contractAddress: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_INK!,
    nftContract: process.env.NEXT_PUBLIC_NFT_CONTRACT_INK!,
    docsPages: [
      'https://docs.inkonchain.com/general/about',
      'https://docs.inkonchain.com/general/network-information',
      'https://docs.inkonchain.com/build/getting-started',
      'https://docs.inkonchain.com/build/transaction-fees',
      'https://docs.inkonchain.com/tools/bridges',
      'https://docs.inkonchain.com/tools/faucets',
      'https://docs.inkonchain.com/faq',
    ],
    heroTitle: 'The Knowledge of Ink',
    heroSubtitle: 'Test your Ink Onchain knowledge',
    heroLabel: 'INK',
    nftMetadataPath: '/nft/ink/1.json',
    nftImage: '/nft/ink.png',
  },
  soneium: {
    name: 'Soneium',
    chainId: 1868,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    color: '#0047FF',
    rpc: 'https://rpc.soneium.org',
    explorer: 'https://soneium.blockscout.com',
    blockscoutApi: 'https://soneium.blockscout.com/api/v2',
    contractAddress: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_SONEIUM!,
    nftContract: process.env.NEXT_PUBLIC_NFT_CONTRACT_SONEIUM!,
    docsPages: [
      'https://docs.soneium.org/docs/builders/overview',
      'https://docs.soneium.org/docs/builders/network-info',
      'https://docs.soneium.org/docs/builders/bridging',
      'https://docs.soneium.org/docs/builders/contracts',
      'https://docs.soneium.org/docs/builders/tools',
      'https://docs.soneium.org/docs/concept/overview',
      'https://docs.soneium.org/docs/users/faq',
    ],
    heroTitle: 'The Knowledge of Soneium',
    heroSubtitle: 'Test your Soneium blockchain knowledge',
    heroLabel: 'SONEIUM',
    nftMetadataPath: '/nft/soneium/1.json',
    nftImage: '/nft/soneium.png',
  },
  base: {
    name: 'Base',
    chainId: 8453,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    color: '#0052ff',
    rpc: 'https://mainnet.base.org',
    explorer: 'https://basescan.org',
    blockscoutApi: 'https://base.blockscout.com/api/v2',
    contractAddress: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_BASE!,
    nftContract: process.env.NEXT_PUBLIC_NFT_CONTRACT_BASE!,
    docsPages: [
      'https://docs.base.org/base-chain/quickstart/why-base',
      'https://docs.base.org/base-account/overview/what-is-base-account',
      'https://docs.base.org/base-chain/network-information/bridges',
      'https://docs.base.org/base-chain/network-information/network-faucets',
      'https://docs.base.org/get-started/block-explorers',
    ],
    heroTitle: 'The Knowledge of Base',
    heroSubtitle: 'Test your Base blockchain knowledge',
    heroLabel: 'BASE',
    nftMetadataPath: '/nft/base/1.json',
    nftImage: '/nft/base.png',
  },
  unichain: {
    name: 'Unichain',
    chainId: 130,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    color: '#ff007a',
    rpc: 'https://mainnet.unichain.org',
    explorer: 'https://uniscan.xyz',
    blockscoutApi: 'https://unichain.blockscout.com/api/v2',
    contractAddress: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_UNICHAIN!,
    nftContract: process.env.NEXT_PUBLIC_NFT_CONTRACT_UNICHAIN!,
    docsPages: [
      'https://docs.unichain.org/docs/unichain',
      'https://docs.unichain.org/docs/unichain/technical-information/network-information',
      'https://docs.unichain.org/docs/unichain/getting-started/setting-up-a-wallet',
      'https://docs.unichain.org/docs/unichain/guides/deploy-a-smart-contract',
      'https://docs.unichain.org/docs/building-on-unichain',
    ],
    heroTitle: 'The Knowledge of Unichain',
    heroSubtitle: 'Test your Unichain knowledge',
    heroLabel: 'UNICHAIN',
    nftMetadataPath: '/nft/unichain/1.json',
    nftImage: '/nft/unichain.png',
  },
  megaeth: {
    name: 'MegaETH',
    chainId: 4326,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    color: '#00ff88',
    rpc: 'https://mainnet.megaeth.com/rpc',
    explorer: 'https://megaeth.blockscout.com',
    blockscoutApi: 'https://megaeth.blockscout.com/api/v2',
    contractAddress: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_MEGAETH!,
    nftContract: process.env.NEXT_PUBLIC_NFT_CONTRACT_MEGAETH!,
    docsPages: [
      'https://docs.megaeth.com/frontier',
      'https://docs.megaeth.com/build',
      'https://docs.megaeth.com/architecture',
    ],
    heroTitle: 'The Knowledge of MegaETH',
    heroSubtitle: 'Test your MegaETH blockchain knowledge',
    heroLabel: 'MEGAETH',
    nftMetadataPath: '/nft/megaeth/1.json',
    nftImage: '/nft/megaeth.png',
  },
  litvm: {
    name: 'LitVM',
    chainId: 4441,
    nativeCurrency: { name: 'zkLTC', symbol: 'zkLTC', decimals: 18 },
    color: '#00F2FE',
    rpc: 'https://liteforge.rpc.caldera.xyz/http',
    explorer: 'https://liteforge.explorer.caldera.xyz',
    blockscoutApi: 'https://liteforge.explorer.caldera.xyz/api/v2',
    contractAddress: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_LITVM!,
    nftContract: process.env.NEXT_PUBLIC_NFT_CONTRACT_LITVM!,
    docsPages: [
      'https://docs.litvm.com/',
      'https://docs.litvm.com/getting-started',
      'https://docs.litvm.com/network-information',
      'https://docs.litvm.com/bridges',
      'https://docs.litvm.com/faucet',
      'https://docs.litvm.com/ecosystem',
    ],
    heroTitle: "The Knowledge of litvm",
    heroSubtitle: "Test your litvm blockchain knowledge",
    heroLabel: 'LITEFORGE',
    nftMetadataPath: '/nft/litvm/1.json',
    nftImage: '/nft/litvm.png',
  },
  arc: {
    name: 'Arc Testnet',
    chainId: 5042002,
    nativeCurrency: { name: 'USD Coin', symbol: 'USDC', decimals: 6 },
    whaleThreshold: 10000,
    color: '#4D8EE9',
    rpc: 'https://rpc.testnet.arc.network',
    explorer: 'https://testnet.arcscan.app',
    blockscoutApi: 'https://testnet.arcscan.app/api/v2',
    contractAddress: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_ARC ?? undefined,
    nftContract: process.env.NEXT_PUBLIC_NFT_CONTRACT_ARC ?? "",
    docsPages: [
      'https://docs.arc.io/arc-chain',
      'https://docs.arc.io/arc/concepts/system-overview',
      'https://docs.arc.io/arc/references/gas-and-fees',
      'https://docs.arc.io/arc/references/connect-to-arc',
      'https://docs.arc.io/arc/tutorials/deploy-contracts',
    ],
    heroTitle: "The Knowledge of Arc",
    heroSubtitle: "Test your Arc blockchain knowledge",
    heroLabel: 'ARC',
    nftMetadataPath: '/nft/arc/1.json',
    nftImage: '/nft/arc.png',
  },
} as const;

type ChainKey = keyof typeof CHAIN_CONFIGS;

const activeChainKey = (process.env.NEXT_PUBLIC_ACTIVE_CHAIN ?? 'ink') as ChainKey;

export const activeChainConfig = CHAIN_CONFIGS[activeChainKey] ?? CHAIN_CONFIGS.ink;
export const isMultiChain = !process.env.NEXT_PUBLIC_ACTIVE_CHAIN;
