const contractEnvKeys = [
  "NEXT_PUBLIC_CONTRACT_ADDRESS_MAINNET",
  "NEXT_PUBLIC_CONTRACT_ADDRESS_INK_MAINNET",
  "NEXT_PUBLIC_CONTRACT_ADDRESS_BASE_MAINNET",
  "NEXT_PUBLIC_CONTRACT_ADDRESS_UNICHAIN",
  "NEXT_PUBLIC_CONTRACT_ADDRESS_LITVM",
  "NEXT_PUBLIC_CONTRACT_ADDRESS_ARC",
  "NEXT_PUBLIC_CONTRACT_ADDRESS_SEPOLIA",
] as const

export function validateContractAddressEnv() {
  for (const key of contractEnvKeys) {
    process.env[key]
  }
}

