/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { QuizScores } from "./QuizScores";
export * as factories from "./factories";
export { QuizScores__factory } from "./factories/QuizScores__factory";
